FROM node:16 as builder

WORKDIR /app

COPY package.json . 

RUN yarn install

COPY . .

ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV

RUN yarn build

FROM nginx

COPY --from=builder /app/build /usr/share/nginx/html